# Generated by Django 4.1.3 on 2022-11-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_chech_in_date_order_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rid',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=2345, max_length=11),
            preserve_default=False,
        ),
    ]
