# Generated by Django 4.1.3 on 2022-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('day1', models.IntegerField()),
                ('day2', models.IntegerField()),
                ('day3', models.IntegerField()),
                ('day4', models.IntegerField()),
                ('day5', models.IntegerField()),
                ('day6', models.IntegerField()),
                ('day7', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='room',
            name='state',
        ),
    ]
