# Generated by Django 3.2.7 on 2022-12-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='0000', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
