# Generated by Django 4.1.3 on 2022-12-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_log_time',
            field=models.DateField(default='2022-12-22'),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_out_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit_date',
            field=models.DateField(),
        ),
    ]
